title: <p align="center"> Sajan Kedia </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/imharshr/">LinkedIn</a> |
  <a href="https://github.com/imharshr">GitHub</a>
  
  <br>   
  Currently working as a software development engineer for Perfios sotware solutions, Bangalore. 
  I am a graduate in B.E, Computer Science Engineering with a CGPA of 8.78. 
  I enjoy problem solving and know many programming languages like python, java, javascript etc. 
  In my free time, I enjoy making videos, meditating and going to the gym.
  <br>
  </p>



theme: jekyll-theme-minimal
